name: Deploy to GitHub Pages
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  deploy:
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@main"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      settings: "pelicanconf.py"
      requirements: "pelican[markdown]"
      theme: "https://github.com/wting/pelican-svbtle.git"
